import { ArrowRight, CheckCircle2, FlaskConical, Globe2, LoaderCircle, LockKeyhole, Mail, Server, ShieldCheck } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '../components/UI';
import { useConnection } from '../connection/ConnectionContext';

export function ConnectionPage() {
  const connection = useConnection(); const navigate = useNavigate();
  const [url, setUrl] = useState(connection.serverUrl); const [email, setEmail] = useState(''); const [code, setCode] = useState('');
  const [step, setStep] = useState<'server' | 'email' | 'code'>('server'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [version, setVersion] = useState('');
  useEffect(() => { setUrl(connection.serverUrl); }, [connection.serverUrl]);
  if (connection.mode === 'booting') return <div className="connection-loading"><LoaderCircle className="spin" /> Restoring connection…</div>;
  if ((connection.mode === 'production' || connection.mode === 'demo') && step === 'server') return <main className="connection-page"><section className="connection-hero"><span className="connection-logo"><ShieldCheck /></span><p className="eyebrow">CONNECTION SETTINGS</p><h1>{connection.mode === 'demo' ? 'Demo mode is active.' : 'Control plane connected.'}</h1><p>{connection.mode === 'demo' ? 'All changes affect sample data only. Connect a VPS to manage production licenses.' : connection.serverUrl}</p></section><section className="connection-card connected-card"><CheckCircle2 className="connected-check" /><h2>{connection.mode === 'demo' ? 'Explicit Demo mode' : 'Production session active'}</h2><p>{connection.mode === 'demo' ? 'No network requests or production writes.' : `${connection.user?.email ?? 'Administrator'} · ${connection.user?.role ?? 'admin'}`}</p><Button onClick={() => void connection.logout()}>{connection.mode === 'demo' ? 'Exit Demo mode' : 'Log out and change server'}</Button><Button variant="ghost" onClick={() => navigate('/')}>Return to Console</Button></section></main>;

  const verifyServer = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await connection.testServer(url); setUrl(result.url); setVersion(result.version); setStep('email'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Connection failed'); } finally { setBusy(false); } };
  const requestCode = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await connection.sendOtp(url, email); setStep('code'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to send code'); } finally { setBusy(false); } };
  const login = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await connection.completeLogin(url, email, code); navigate('/'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Login failed'); } finally { setBusy(false); } };

  return <main className="connection-page"><section className="connection-hero"><span className="connection-logo"><ShieldCheck /></span><p className="eyebrow">LICENSEHUB CONSOLE</p><h1>Connect your control plane.</h1><p>Point this Console at your LicenseHub VPS, verify the server, then authenticate with your administrator email.</p><div className="security-points"><span><LockKeyhole /> Protected browser session</span><span><Globe2 /> HTTPS required outside localhost</span><span><Server /> Endpoint can change anytime</span></div></section>
    <section className="connection-card"><div className="connection-steps"><span className={step === 'server' ? 'current' : 'done'}>1</span><i /><span className={step === 'email' ? 'current' : step === 'code' ? 'done' : ''}>2</span><i /><span className={step === 'code' ? 'current' : ''}>3</span></div>
      {step === 'server' && <form onSubmit={(event) => void verifyServer(event)}><div className="connection-title"><Server /><div><h2>Server connection</h2><p>Enter the public origin of your LicenseHub VPS.</p></div></div><label>LicenseHub server URL<div className="connection-input"><Globe2 /><input required autoFocus type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://license.yourdomain.com" /></div></label>{error && <p className="connection-error">{error}</p>}<Button type="submit" busy={busy}>Test connection <ArrowRight /></Button><button type="button" className="demo-entry" onClick={() => { connection.enterDemo(); navigate('/'); }}><FlaskConical /> Explore Demo mode <small>Uses sample data only</small></button></form>}
      {step === 'email' && <form onSubmit={(event) => void requestCode(event)}><div className="connection-title"><CheckCircle2 className="success-icon" /><div><h2>Server verified</h2><p>{url} · v{version || 'unknown'}</p></div></div><label>Administrator email<div className="connection-input"><Mail /><input required autoFocus type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="admin@yourdomain.com" /></div></label>{error && <p className="connection-error">{error}</p>}<div className="connection-buttons"><Button type="button" variant="ghost" onClick={() => setStep('server')}>Back</Button><Button type="submit" busy={busy}>Send one-time code <ArrowRight /></Button></div></form>}
      {step === 'code' && <form onSubmit={(event) => void login(event)}><div className="connection-title"><Mail /><div><h2>Check your inbox</h2><p>A six-digit code was sent to {email}.</p></div></div><label>One-time code<div className="connection-input otp-input"><LockKeyhole /><input required autoFocus inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} placeholder="000000" /></div></label>{error && <p className="connection-error">{error}</p>}<div className="connection-buttons"><Button type="button" variant="ghost" onClick={() => setStep('email')}>Back</Button><Button type="submit" busy={busy}>Open Console <ArrowRight /></Button></div></form>}
    </section></main>;
}
